# Generated by Django 3.1 on 2020-09-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0008_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=models.BooleanField(default=False),
        ),
    ]
