# Generated by Django 3.1 on 2020-09-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0009_auto_20200908_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference',
            field=models.URLField(blank=True, max_length=120),
        ),
    ]
