# Generated by Django 3.1 on 2020-09-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0010_user_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reference',
            new_name='cv',
        ),
    ]
