# Generated by Django 3.1 on 2020-09-08 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0011_auto_20200908_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=120, help_text='Value must be in CM, between 120-250cm', validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(120)]),
        ),
    ]
