# Generated by Django 3.1 on 2020-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0013_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='flare',
            field=models.CharField(default='General', max_length=30),
        ),
    ]
