# Generated by Django 3.1 on 2020-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0014_posts_flare'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='video_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
