# Generated by Django 3.1 on 2020-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0016_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='upvoted',
            field=models.BooleanField(default=True),
        ),
    ]
