# Generated by Django 3.1 on 2020-09-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0021_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
